import React, { Component, PropTypes } from "react";
import logo from "../address1.png";
import footImg from "../footer.png";
import UserContext from "../Context/UserContext";
import LoginInsideHeader from "./LoginInsideHeader";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import "bootstrap/dist/css/bootstrap.min.css";
import { WhatsappShareButton, WhatsappIcon } from "react-share";

export default class MyDocument extends Component {
  constructor(props) {
    super(props);
    this.printDocument = this.printDocument.bind(this);
    this.state = {
      pdf: "",
      adminAddress:''
    };
  }

  exportAsPicture(details) {
    const input = document.getElementById("divToPrint");
    html2canvas(input).then((canvas) => {
      console.log(canvas.toDataURL(), "con");
      this.simulateDownloadImageClick(
        canvas.toDataURL(),
        `${details.name} Jathagam.png`
      );
    });
  }

  simulateDownloadImageClick(uri, filename) {
    var link = document.createElement("a");
    if (typeof link.download !== "string") {
      window.open(uri);
    } else {
      link.href = uri;
      link.download = filename;
      this.accountForFirefox(this.clickLink, link);
    }
  }

  clickLink(link) {
    link.click();
  }

  accountForFirefox(click) {
    // wrapper function
    let link = arguments[1];
    document.body.appendChild(link);
    click(link);
    document.body.removeChild(link);
  }

  downloadDocument(details) {
    const input = document.getElementById("divToPrint");

    html2canvas(input).then((canvas) => {
      var contentWidth = canvas.width;
      var contentHeight = canvas.height;

      //One page pdf shows the height of canvas generated by html page;
      var pageHeight = (contentWidth / 592.28) * 841.89;
      //html page height without pdf generation
      var leftHeight = contentHeight;
      //Page offset
      var position = 0;
      //a4 paper size [595.28841.89], width and height of image in pdf of canvas generated by html page
      var imgWidth = 595.28;
      var imgHeight = (592.28 / contentWidth) * contentHeight;

      //Return picture dataURL, parameters: picture format and sharpness (0-1)
      var pageData = canvas.toDataURL("image/png", 1.0);

      //Direction is vertical by default, dimension ponits, format A4 [595.28841.89]
      var pdf = new jsPDF("", "pt", "a4");

      //There are two heights to distinguish, one is the actual height of the html page, and the height of the generated pdf page (841.89)
      //When the content does not exceed the display range of one page of pdf, paging is not required
      if (leftHeight < pageHeight) {
        pdf.addImage(pageData, "PNG", 0, 0, imgWidth, imgHeight);
      } else {
        while (leftHeight > 0) {
          pdf.addImage(pageData, "PNG", 0, position, imgWidth, imgHeight);
          leftHeight -= pageHeight;
          position -= 841.89;
          //Avoid adding blank pages
          if (leftHeight > 0) {
            pdf.addPage();
          }
        }
      }
      pdf.save(`${details.name} Jathagam.pdf`);
      //
      // console.log(pdf.output("blob"), "adarsh");
      // console.log(pdf.output("datauristring"), "adarsh");
      // console.log(pdf.save(`${details.name}Jathagam.pdf`));
    });
  }
  printDocument(details) {
    const input = document.getElementById("divToPrint");

    html2canvas(input).then((canvas) => {
      var contentWidth = canvas.width;
      var contentHeight = canvas.height;

      //One page pdf shows the height of canvas generated by html page;
      var pageHeight = (contentWidth / 592.28) * 841.89;
      //html page height without pdf generation
      var leftHeight = contentHeight;
      //Page offset
      var position = 0;
      //a4 paper size [595.28841.89], width and height of image in pdf of canvas generated by html page
      var imgWidth = 595.28;
      var imgHeight = (592.28 / contentWidth) * contentHeight;

      //Return picture dataURL, parameters: picture format and sharpness (0-1)
      var pageData = canvas.toDataURL("image/png", 1.0);

      //Direction is vertical by default, dimension ponits, format A4 [595.28841.89]
      var pdf = new jsPDF("", "pt", "a4");

      //There are two heights to distinguish, one is the actual height of the html page, and the height of the generated pdf page (841.89)
      //When the content does not exceed the display range of one page of pdf, paging is not required
      if (leftHeight < pageHeight) {
        pdf.addImage(pageData, "PNG", 0, 0, imgWidth, imgHeight);
      } else {
        while (leftHeight > 0) {
          pdf.addImage(pageData, "PNG", 0, position, imgWidth, imgHeight);
          leftHeight -= pageHeight;
          position -= 841.89;
          //Avoid adding blank pages
          if (leftHeight > 0) {
            pdf.addPage();
          }
        }
      }
      window.open(pdf.output("bloburl"), "_blank");

      //
      // console.log(pdf.output("blob"), "adarsh");
      // console.log(pdf.output("datauristring"), "adarsh");
      // console.log(pdf.save(`${details.name}Jathagam.pdf`));
    });
  }

  readFileData = (file) => {
    console.log(file, "file");
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        resolve(e.target.result);
      };
      reader.onerror = (err) => {
        reject(err);
      };
      reader.readAsDataURL(file);
    });
  };

  async componentDidMount() {
    const { details } = this.context;
    console.log(details, "det");
    fetch("http://localhost:3000/single-admin-detail", {
      method: "POST",
      crossDomain: true,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        "Access-Control-Allow-Origin": "*",
      },
    })
      .then((res) => res.json())
      .then((data)=>{
       
        this.setState({
          adminAddress:data.data[0].address
        })
        console.log(data,'data')
    });





    const input = document.getElementById("divToPrint");
    html2canvas(input).then(async (canvas) => {
      console.log(canvas.toDataURL(), "con");

      const response = await fetch(canvas.toDataURL());
      // here image is url/location of image
      const blob = await response.blob();
      const file = new File([blob], "share.jpg", { type: blob.type });
      console.log(file, "vik");
      this.setState({
        pdf: file,
      });
    });
  }
  handleShareButton = () => {
    // Check if navigator.share is supported by the browser
    if (navigator.share) {
      console.log("Congrats! Your browser supports Web Share API");
      navigator
        .share({
          title: "View my Jagatham",
          url: `https://share.toogoodtogo.com/store/1006/milestones/meals-saved/`,
        })
        .then(() => {
          console.log("Sharing successfull");
        })
        .catch(() => {
          console.log("Sharing failed");
        });
    } else {
      console.log("Sorry! Your browser does not support Web Share API");
    }
  };

  render() {
    const { details } = this.context;
    // const url = this.state.pdf;
    return (
      <div>
        <LoginInsideHeader />
        <div className="mb5 print-div">
          <div className="print-el wp">
            <WhatsappShareButton
              title="Share"
              url={this.state.pdf}
              media="https://firebasestorage.googleapis.com/v0/b/dsdnewsapi.appspot.com/o/projectPics%2Ff862995d-f93f-4684-8ad4-52e2fde6324c.png?alt=media&token=287de96d-b2b8-4c7d-a327-5143f7ad4ac5"
              imageUrl="https://firebasestorage.googleapis.com/v0/b/dsdnewsapi.appspot.com/o/projectPics%2Ff862995d-f93f-4684-8ad4-52e2fde6324c.png?alt=media&token=287de96d-b2b8-4c7d-a327-5143f7ad4ac5"
              mediaUrl="https://firebasestorage.googleapis.com/v0/b/dsdnewsapi.appspot.com/o/projectPics%2Ff862995d-f93f-4684-8ad4-52e2fde6324c.png?alt=media&token=287de96d-b2b8-4c7d-a327-5143f7ad4ac5"
            >
              <WhatsappIcon size={40} round={true}></WhatsappIcon>
            </WhatsappShareButton>
          </div>
          <div className="print-el wp">
            {" "}
            <button onClick={() => this.downloadDocument(details)}>
              Download Pdf 
            </button>{" "}
          </div>

          <div className="print-el wp">
            <button onClick={() => this.exportAsPicture(details)}>
              Download as Image
            </button>{" "}
          </div>

          <div className="print-el wp">
            <button onClick={() => this.printDocument(details)}>
              Print Pdf
            </button>{" "}
          </div>
        </div>

        <div
          id="divToPrint"
          className="mt4"
          style={{
            backgroundColor: "white",
            width: "210mm",
            minHeight: "298.3mm",
            marginLeft: "auto",
            marginRight: "auto",
          }}
        >
          <div className="divToPrint2">
            <div className="row pdf-main">
              <div className="pdf-top-img">
                <img
                  src={logo}
                  alt="GANESHKONGUMATRIMONY"
                  height="auto"
                  width="100%"
                />
                <div className='manual-address'><h6>{this.state.adminAddress} </h6></div>
                <div className="row pdf-info">
                 
                  <div className="col-md-12 pdf-info-text1">
                  <h4>Registered Date</h4>&nbsp;   
                    <h3>
                      {details.regDate == "" || details.regDate == undefined
                        ? "-"
                        : details.regDate}
                    </h3>
                  </div>
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col-md-6 pdf-info-div">
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Registered Date</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.regDate == "" || details.regDate == undefined
                        ? "-"
                        : details.regDate}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Registration Number</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.regNumber == "" || details.regNumber == undefined
                        ? "-"
                        : details.regNumber}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Name</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>{details.name == "" ? "-" : details.name}</h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Date Of Birth</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.dob == ""
                        ? "-"
                        : details.basic.dob}{" "}
                      {details.horoscope == undefined
                        ? "-"
                        : details.horoscope.birthtime == ""
                        ? ""
                        : details.horoscope.birthtime}
                    </h3>
                  </div>
                </div>

                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Day Of Birth</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.dayOfBirth == "" ||
                          details.basic.dayOfBirth == undefined
                        ? "-"
                        : details.basic.dayOfBirth}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Birth Place</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.horoscope == undefined
                        ? "-"
                        : details.horoscope.birthplace == ""
                        ? "-"
                        : details.horoscope.birthplace}
                    </h3>
                  </div>
                </div>

                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Rasi</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.religion == undefined
                        ? "-"
                        : details.religion.partrassi == ""
                        ? "-"
                        : details.religion.partrassi}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Nakshatram</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.religion == undefined
                        ? "-"
                        : details.religion.partnakshatram == ""
                        ? "-"
                        : details.religion.partnakshatram}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Father</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.family == undefined
                        ? "-"
                        : details.family.partfalive == "" ||
                          details.family.partfalive == undefined
                        ? "-"
                        : details.family.partfalive}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Mother</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.family == undefined
                        ? "-"
                        : details.family.partmalive == "" ||
                          details.family.partmalive == undefined
                        ? "-"
                        : details.family.partmalive}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-horo">
                  <div className="col-md-3 pdf-horo-el">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo12.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo1.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo2.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo3.join(" ")}
                  </div>

                  <div className="col-md-3 pdf-horo-el-1 mid-div ">
                    <div className="col-md-12 mid-div-in  ">
                      {details.boxHoroscope == undefined
                        ? ""
                        : details.boxHoroscope.horo11.join(" ")}
                    </div>
                    <div className="col-md-12  mid-div-in   ">
                      {details.boxHoroscope == undefined
                        ? ""
                        : details.boxHoroscope.horo10.join(" ")}
                    </div>
                  </div>

                  <div className="col-md-6   pdf-horo-el-1 mid-main">Rasi</div>
                  <div className="col-md-3 pdf-horo-el-1 mid-div rm-ri ">
                    <div className="col-md-12 mid-div-in  ">
                      {details.boxHoroscope == undefined
                        ? ""
                        : details.boxHoroscope.horo4.join(" ")}
                    </div>
                    <div className="col-md-12  mid-div-in   ">
                      {details.boxHoroscope == undefined
                        ? ""
                        : details.boxHoroscope.horo5.join(" ")}
                    </div>
                  </div>
                  <div className="col-md-3 pdf-horo-el-2">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo9.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo8.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo7.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2 rm-ri">
                    {details.boxHoroscope == undefined
                      ? ""
                      : details.boxHoroscope.horo6.join(" ")}
                  </div>
                </div>
              </div>

              <div className="col-md-6  pdf-info-div">
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Registered Person</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>500</h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Gender</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.gender == undefined
                        ? "-"
                        : details.gender == "" || details.gender == undefined
                        ? "-"
                        : details.gender}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Marrital Status</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.married == "" ||
                          details.basic.married == undefined
                        ? "-"
                        : details.basic.married}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Height</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.height == "" ||
                          details.basic.height == undefined
                        ? "-"
                        : details.basic.height}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Complexion</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.complexion == "" ||
                          details.basic.complexion == undefined
                        ? "-"
                        : details.basic.complexion}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Weight</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.weight == "" ||
                          details.basic.weight == undefined
                        ? "-"
                        : details.basic.weight}
                    </h3>
                  </div>
                </div>

                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Blood Group</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.bloodGroup == "" ||
                          details.basic.bloodGroup == undefined
                        ? "-"
                        : details.basic.bloodGroup}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Education</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.professional == undefined
                        ? "-"
                        : details.professional.parteducation == "" ||
                          details.professional.parteducation == undefined
                        ? "-"
                        : details.professional.parteducation}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Kulam</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.religion == undefined
                        ? "-"
                        : details.religion.partkulamtemple == "" ||
                          details.religion.partkulamtemple == undefined
                        ? "-"
                        : details.religion.partkulamtemple}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Age</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.basic == undefined
                        ? "-"
                        : details.basic.age == "" ||
                          details.basic.age == undefined
                        ? "-"
                        : details.basic.age}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-horo">
                  <div className="col-md-3 pdf-horo-el">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo12.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo1.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo2.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo3.join(" ")}
                  </div>

                  <div className="col-md-3 pdf-horo-el-1 mid-div ">
                    <div className="col-md-12 mid-div-in  ">
                      {details.boxHoroscopeSecond == undefined
                        ? ""
                        : details.boxHoroscopeSecond.horo11.join(" ")}
                    </div>
                    <div className="col-md-12  mid-div-in   ">
                      {details.boxHoroscopeSecond == undefined
                        ? ""
                        : details.boxHoroscopeSecond.horo10.join(" ")}
                    </div>
                  </div>

                  <div className="col-md-6   pdf-horo-el-1 mid-main">
                    Navasam
                  </div>
                  <div className="col-md-3 pdf-horo-el-1 mid-div rm-ri ">
                    <div className="col-md-12 mid-div-in  ">
                      {details.boxHoroscopeSecond == undefined
                        ? ""
                        : details.boxHoroscopeSecond.horo4.join(" ")}
                    </div>
                    <div className="col-md-12  mid-div-in   ">
                      {details.boxHoroscopeSecond == undefined
                        ? ""
                        : details.boxHoroscopeSecond.horo5.join(" ")}
                    </div>
                  </div>
                  <div className="col-md-3 pdf-horo-el-2">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo9.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo8.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo7.join(" ")}
                  </div>
                  <div className="col-md-3  pdf-horo-el-2 rm-ri">
                    {details.boxHoroscopeSecond == undefined
                      ? ""
                      : details.boxHoroscopeSecond.horo6.join(" ")}
                  </div>
                </div>
              </div>
              <div className="col-md-6 pdf-btm-con">
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Direction Having</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>-</h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Working Status</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.professional == undefined
                        ? "-"
                        : details.professional.partsector == ""
                        ? "-"
                        : details.professional.partsector}
                      {/* {details.professional==undefined?'-':details.professional.partindustry==''?'':details.professional.partindustry} */}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Assets</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.family == undefined
                        ? "-"
                        : details.family.partassets == "" ||
                          details.family.partassets == undefined
                        ? "-"
                        : details.family.partassets}
                    </h3>
                  </div>
                </div>
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Expectation</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>-</h3>
                  </div>
                </div>
                {/* <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Nakshatram</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.religion == undefined
                        ? "-"
                        : details.religion.partnakshatram == "" ||
                          details.religion.partnakshatram == undefined
                        ? "-"
                        : details.religion.partnakshatram}
                    </h3>
                  </div>
                </div> */}
                <div className="row pdf-info">
                  <div className="col-md-12 pdf-info-text">
                    <h4>
                      Let's Look at the matching star{" "}
                      <b>
                        {details.partnerpreference == undefined
                          ? ""
                          : details.partnerpreference.partastrology.join(", ")}
                      </b>
                    </h4>
                  </div>
                </div>
              </div>
              <div className="col-md-6 pdf-btm-con">
                <div className="row pdf-info">
                  <div className="col-md-6 pdf-info-text">
                    <h4>Monthly Income</h4>
                  </div>
                  <div className="col-md-6 pdf-info-text">
                    <h3>
                      {details.professional == undefined
                        ? "-"
                        : details.professional.partmonthincome == "" ||
                          details.professional.partmonthincome == undefined
                        ? "-"
                        : details.professional.partmonthincome.label}
                    </h3>
                  </div>
                </div>
              </div>

              <div className="pdf-btm">
                <div>
                  Note: Our company operates with the help of the Kongu Wedding
                  Organizers team. After the marriage is confirmed, the service
                  charge will be Rs.500 / - (minimum (25000) for the female
                  horoscope and Rs.1000 / - for the male horoscope (minimum
                  (50000)) separately,
                  <b> Print Date: {new Date().toLocaleString() + ""}</b>
                </div>

                <div className="pdf-btm-img">
                  <img
                    src={footImg}
                    alt="GANESHKONGUMATRIMONY"
                    height="auto"
                    width="100%"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
MyDocument.contextType = UserContext;
